<a href="https://colab.research.google.com/github/patrickhamzaokello/ColabFavourites/blob/main/GtbankFraud1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [2]:
df = pd.read_csv('/content/GTWORLDTRANSACTIONS.csv')

In [3]:
df.head()

,TransID,CustomerName,CustomerAccount,BeneficiaryName,BeneficiaryAccountNumber,BeneficiaryBank,BeneficiaryBankBranch,BeneficiaryBankAddress,BeneficiaryAddress,BeneficiaryBankCode,...,RecordDate,PaymentDate,Isposted,IsLoggedIntoEFTPS,Charges,Status,Remarks2,TransferType,ForexType,ForexRate
0,GTB0101202308011478syrg8qwg,JORDAN KALYABE,218/144863/1/5003/0,JORDAN AND TREVOR AND SAM AND BENJA,219152227150030,GTBANK,,,,,...,NaN,2023-01-01 08:01:56.233,1,0,0,SUCCESS,<RESPONSE><CODE>1000</CODE><STATUS>SUCCESS</ST...,NaN,NaN,NaN
1,GTB01012023080842E248CF89-4,MUSUNGU MARK ANTONNY,218/157278/1/5107/0,,0784981244,MTN,,,,,...,NaN,2023-01-01 08:09:24.893,1,0,0,SUCCESS,<RESPONSE><CODE>1000</CODE><STATUS>SUCCESS</ST...,NaN,NaN,NaN
2,GTB0101202308314878syrg8qwg,KASUJJA.ARNOLD,212/140984/1/5001/0,KASUJJAARNOLD,218153955150030,GTBANK,,,,,...,NaN,2023-01-01 08:32:29.813,1,0,0,SUCCESS,<RESPONSE><CODE>1000</CODE><STATUS>SUCCESS</ST...,NaN,NaN,NaN
3,GTB0101202308325778syrg8qwg,KASUJJA ARNOLD,218/153955/1/5003/0,KASUJJA ARNOLD,218/153955/1/5107/0,GTBANK,,,,,...,NaN,2023-01-01 08:33:38.830,1,0,0,SUCCESS,<RESPONSE><CODE>1000</CODE><STATUS>SUCCESS</ST...,NaN,NaN,NaN
4,GTB0101202308343978syrg8qwg,KASUJJA ARNOLD,218/153955/1/5107/0,,0778502199,MTN,,,,,...,NaN,2023-01-01 08:35:21.490,1,0,0,SUCCESS,<RESPONSE><CODE>1000</CODE><STATUS>SUCCESS</ST...,NaN,NaN,NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42810 entries, 0 to 42809
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TransID                   42810 non-null  object
 1   CustomerName              42810 non-null  object
 2   CustomerAccount           42810 non-null  object
 3   BeneficiaryName           42810 non-null  object
 4   BeneficiaryAccountNumber  42810 non-null  object
 5   BeneficiaryBank           42810 non-null  object
 6   BeneficiaryBankBranch     42810 non-null  object
 7   BeneficiaryBankAddress    42810 non-null  object
 8   BeneficiaryAddress        42810 non-null  object
 9   BeneficiaryBankCode       42810 non-null  object
 10  Amount                    42810 non-null  float64
 11  Currency                  42810 non-null  object
 12  Remarks                   42810 non-null  object
 13  TransType                 42810 non-null  object
 14  PaymentMode               42810 non-null  object
 15  RecordDate                0 non-null      float64
 16  PaymentDate               42810 non-null  object
 17  Isposted                  42810 non-null  int64
 18  IsLoggedIntoEFTPS         42810 non-null  int64
 19  Charges                   42810 non-null  int64
 20  Status                    42810 non-null  object
 21  Remarks2                  42492 non-null  object
 22  TransferType              528 non-null    object
 23  ForexType                 528 non-null    object
 24  ForexRate                 346 non-null    float64
dtypes: float64(3), int64(3), object(19)
memory usage: 8.2+ MB

In [21]:
#get only selected columns transID, customerName, Amount
selected_df = df[['TransID', 'CustomerAccount', 'CustomerName',  'BeneficiaryBank', 'Amount', 'Currency', 'TransType', 'PaymentDate', 'Status']]

selected_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42810 entries, 0 to 42809
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransID          42810 non-null  object
 1   CustomerAccount  42810 non-null  object
 2   CustomerName     42810 non-null  object
 3   BeneficiaryBank  42810 non-null  object
 4   Amount           42810 non-null  float64
 5   Currency         42810 non-null  object
 6   TransType        42810 non-null  object
 7   PaymentDate      42810 non-null  object
 8   Status           42810 non-null  object
dtypes: float64(1), object(8)
memory usage: 2.9+ MB

In [23]:
#rename columns PaymentDate to date, Amount to amount, TransID to id
selected_df = selected_df.rename(columns={'PaymentDate': 'date', 'Amount': 'amount','BeneficiaryBank': 'type', 'CustomerAccount': 'user_id','CustomerName': 'user_name'})

selected_df.head()

,TransID,user_id,user_name,type,amount,Currency,TransType,date,Status
0,GTB0101202308011478syrg8qwg,218/144863/1/5003/0,JORDAN KALYABE,GTBANK,150000.0,,INTERNAL,2023-01-01 08:01:56.233,SUCCESS
1,GTB01012023080842E248CF89-4,218/157278/1/5107/0,MUSUNGU MARK ANTONNY,MTN,25000.0,UGX,B2W,2023-01-01 08:09:24.893,SUCCESS
2,GTB0101202308314878syrg8qwg,212/140984/1/5001/0,KASUJJA.ARNOLD,GTBANK,50000.0,,INTERNAL,2023-01-01 08:32:29.813,SUCCESS
3,GTB0101202308325778syrg8qwg,218/153955/1/5003/0,KASUJJA ARNOLD,GTBANK,54000.0,UGX,OWN,2023-01-01 08:33:38.830,SUCCESS
4,GTB0101202308343978syrg8qwg,218/153955/1/5107/0,KASUJJA ARNOLD,MTN,31000.0,UGX,B2W,2023-01-01 08:35:21.490,SUCCESS

In [44]:
def engineer_fraud_features(df, user_baselines=None, risk_thresholds=None):
    """
    Create features for fraud detection and flag suspicious transactions.

    Parameters:
    df: DataFrame with columns [transaction_id, date, amount, user_id, type, is_fraud]
    user_baselines: dict with user-specific thresholds (optional)
    risk_thresholds: dict with risk scoring thresholds (optional)

    Returns:
    DataFrame with engineered features and fraud flags
    """
    # Convert date to datetime if not already
    df['date'] = pd.to_datetime(df['date'])

    # Create copy to avoid modifications to original data
    features = df.copy()

    # [Previous feature engineering code remains the same until the end]
    user_stats = df.groupby('user_id').agg({
        'amount': ['mean', 'std', 'max', 'count'],
        'type': lambda x: x.value_counts().index[0]  # most common type
    }).reset_index()

    user_stats.columns = ['user_id', 'user_avg_amount', 'user_std_amount',
                         'user_max_amount', 'user_transaction_count',
                         'user_preferred_type']

    features = features.merge(user_stats, on='user_id', how='left')

    # Time-based features
    features['hour'] = features['date'].dt.hour
    features['day_of_week'] = features['date'].dt.dayofweek
    features['is_weekend'] = features['day_of_week'].isin([5, 6]).astype(int)
    features['is_night'] = ((features['hour'] >= 23) | (features['hour'] <= 4)).astype(int)

    # Amount-based features
    features['amount_vs_user_avg'] = features['amount'] / features['user_avg_amount']
    features['amount_vs_user_max'] = features['amount'] / features['user_max_amount']
    features['is_amount_outlier'] = (
        features['amount'] > features['user_avg_amount'] + 2 * features['user_std_amount']
    ).astype(int)

    # Transaction pattern features
    features['time_since_last_tx'] = features.groupby('user_id')['date'].diff().dt.total_seconds() / 3600

    def count_recent_tx(group, hours=24):
        # Reset index to access 'date' as a column
        group = group.reset_index(drop=True)
        def count_for_row(row):
            time_window = row['date'] - timedelta(hours=hours)
            return len(group[(group['date'] <= row['date']) &
                           (group['date'] > time_window)])
        return group.apply(count_for_row, axis=1)


    # features['tx_last_24h'] = features.groupby('user_id').apply(
    #     lambda x: count_recent_tx(x)
    # ).reset_index(level=0, drop=True)

    features['tx_last_24h'] = features.groupby('user_id').apply(
        lambda x: count_recent_tx(x)
    ).values

    # Type-based features
    features['is_preferred_type'] = (
        features['type'] == features['user_preferred_type']
    ).astype(int)

    # Amount velocity
    def amount_velocity(group, hours=24):
        # Reset index to access 'date' as a column
        group = group.reset_index(drop=True)
        def velocity_for_row(row):
            time_window = row['date'] - timedelta(hours=hours)
            recent_amount = group[(group['date'] <= row['date']) &
                                (group['date'] > time_window)]['amount'].sum()
            return recent_amount / (group['user_avg_amount'].iloc[0] * hours/24)
        return group.apply(velocity_for_row, axis=1) # Apply to each row

    # features['amount_velocity_24h'] = features.groupby('user_id').apply(
    #     lambda x: amount_velocity(x)
    # ).reset_index(level=0, drop=True)

    features['amount_velocity_24h'] = features.groupby('user_id').apply(
        lambda x: amount_velocity(x)
    ).values

    # Use default risk thresholds if none provided
    if risk_thresholds is None:
        risk_thresholds = {
            'amount_multiplier': 3,      # transactions > 3x user average
            'velocity_threshold': 2,      # velocity > 2x daily average
            'tx_frequency_threshold': 5,  # > 5 transactions in 24h
            'min_risk_score': 0.7        # minimum risk score to flag as fraud
        }

    # Calculate risk scores (0 to 1) for different aspects
    features['amount_risk'] = 1 - (1 / (1 + np.exp(features['amount_vs_user_avg'] - risk_thresholds['amount_multiplier'])))
    features['velocity_risk'] = 1 - (1 / (1 + np.exp(features['amount_velocity_24h'] - risk_thresholds['velocity_threshold'])))
    features['frequency_risk'] = 1 - (1 / (1 + np.exp(features['tx_last_24h'] - risk_thresholds['tx_frequency_threshold'])))
    features['time_risk'] = features['is_night'] * 0.3 + features['is_weekend'] * 0.2
    features['type_risk'] = (1 - features['is_preferred_type']) * 0.5

    # Calculate overall risk score
    features['risk_score'] = (
        features['amount_risk'] * 0.35 +    # Amount anomalies weighted highest
        features['velocity_risk'] * 0.25 +  # Velocity is next most important
        features['frequency_risk'] * 0.20 + # Frequency is third
        features['time_risk'] * 0.10 +      # Time-based risks weighted lower
        features['type_risk'] * 0.10        # Type-based risks weighted lower
    )

    # Flag transactions as potentially fraudulent based on risk score
    features['is_suspicious'] = (features['risk_score'] >= risk_thresholds['min_risk_score']).astype(int)

    # Add user baseline violations if provided
    if user_baselines:
        for user_id, baseline in user_baselines.items():
            mask = features['user_id'] == user_id
            if 'amount_threshold' in baseline:
                features.loc[mask, 'exceeds_user_threshold'] = (
                    features.loc[mask, 'amount'] > baseline['amount_threshold']
                ).astype(int)
                # Automatically flag as suspicious if user threshold is exceeded
                features.loc[mask & (features['exceeds_user_threshold'] == 1), 'is_suspicious'] = 1

            if 'allowed_types' in baseline:
                features.loc[mask, 'is_allowed_type'] = (
                    features.loc[mask, 'type'].isin(baseline['allowed_types'])
                ).astype(int)
                # Automatically flag as suspicious if transaction type not allowed
                features.loc[mask & (features['is_allowed_type'] == 0), 'is_suspicious'] = 1

    # Drop intermediate columns
    features = features.drop(['date', 'user_preferred_type'], axis=1)

    return features

In [55]:
selected_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42810 entries, 0 to 42809
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TransID    42810 non-null  object
 1   user_id    42810 non-null  object
 2   user_name  42810 non-null  object
 3   type       42810 non-null  object
 4   amount     42810 non-null  float64
 5   Currency   42810 non-null  object
 6   TransType  42810 non-null  object
 7   date       42810 non-null  datetime64[ns]
 8   Status     42810 non-null  object
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 2.9+ MB

In [56]:
# Basic usage with default risk thresholds
features = engineer_fraud_features(selected_df)

<ipython-input-44-1e6ebcd4f255>:61: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  features['tx_last_24h'] = features.groupby('user_id').apply(
<ipython-input-44-1e6ebcd4f255>:78: RuntimeWarning: invalid value encountered in scalar divide
  return recent_amount / (group['user_avg_amount'].iloc[0] * hours/24)
<ipython-input-44-1e6ebcd4f255>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  features['amount_velocity_24h'] = features.groupby('user_id').apply(

In [59]:
features

,TransID,user_id,user_name,type,amount,Currency,TransType,Status,user_avg_amount,user_std_amount,...,tx_last_24h,is_preferred_type,amount_velocity_24h,amount_risk,velocity_risk,frequency_risk,time_risk,type_risk,risk_score,is_suspicious
0,GTB0101202308011478syrg8qwg,218/144863/1/5003/0,JORDAN KALYABE,GTBANK,150000.0,,INTERNAL,SUCCESS,655515.362776,1.536056e+06,...,1,0,2.168385,0.058902,0.541997,0.017986,0.2,0.5,0.229712,0
1,GTB01012023080842E248CF89-4,218/157278/1/5107/0,MUSUNGU MARK ANTONNY,MTN,25000.0,UGX,B2W,SUCCESS,51251.640625,1.097380e+05,...,2,1,4.336770,0.075007,0.911877,0.047426,0.2,0.0,0.283707,0
2,GTB0101202308314878syrg8qwg,212/140984/1/5001/0,KASUJJA.ARNOLD,GTBANK,50000.0,,INTERNAL,SUCCESS,44532.166667,3.028081e+04,...,1,1,0.731610,0.132709,0.219533,0.017986,0.2,0.0,0.124929,0
3,GTB0101202308325778syrg8qwg,218/153955/1/5003/0,KASUJJA ARNOLD,GTBANK,54000.0,UGX,OWN,SUCCESS,128410.151376,4.084552e+05,...,1,1,3.499386,0.070471,0.817483,0.017986,0.2,0.0,0.252633,0
4,GTB0101202308343978syrg8qwg,218/153955/1/5107/0,KASUJJA ARNOLD,MTN,31000.0,UGX,B2W,SUCCESS,324390.259259,6.873366e+05,...,1,1,0.072280,0.051935,0.127003,0.017986,0.2,0.0,0.073525,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42805,GTB12312023232750b026679f12,211/132085/1/5003/1,NANTEZA DORA,MTN,10000.0,UGX,B2W,SUCCESS,250708.277078,6.341082e+05,...,2,0,0.366972,0.049261,0.163416,0.047426,0.5,0.5,0.167580,0
42806,GTB12312023233050b026679f12,211/132085/1/5003/1,NANTEZA DORA,AIRTEL,10000.0,UGX,B2W,SUCCESS,250708.277078,6.341082e+05,...,1,1,0.293578,0.049261,0.153628,0.017986,0.5,0.0,0.109246,0
42807,GTB12312023233204596675de40,211/103956/1/5107/0,rachel murungi,AIRTEL,6000.0,UGX,B2W,SUCCESS,199067.796610,4.044539e+05,...,2,0,0.587156,0.048806,0.195786,0.047426,0.5,0.5,0.175514,0
42808,GTB123120232334055d7c52e59f,218/160019/1/5003/0,Hellen,MTN,11000.0,UGX,B2W,SUCCESS,40068.367347,6.096214e+04,...,3,1,0.880734,0.061487,0.246147,0.119203,0.5,0.0,0.156898,0
42809,GTB12312023234210cca9f5c7df,219/153846/1/5003/0,MANIRAMPA,MTN,30000.0,UGX,B2W,SUCCESS,85000.000000,5.590170e+04,...,4,1,1.174312,0.066171,0.304558,0.268941,0.5,0.0,0.203087,0

In [63]:
# View suspicious transactions
suspicious_tx = features[features['is_suspicious'] == 1]

suspicious_tx.info()

<class 'pandas.core.frame.DataFrame'>
Index: 98 entries, 1694 to 42614
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   TransID                 98 non-null     object
 1   user_id                 98 non-null     object
 2   user_name               98 non-null     object
 3   type                    98 non-null     object
 4   amount                  98 non-null     float64
 5   Currency                98 non-null     object
 6   TransType               98 non-null     object
 7   Status                  98 non-null     object
 8   user_avg_amount         98 non-null     float64
 9   user_std_amount         98 non-null     float64
 10  user_max_amount         98 non-null     float64
 11  user_transaction_count  98 non-null     int64
 12  hour                    98 non-null     int32
 13  day_of_week             98 non-null     int32
 14  is_weekend              98 non-null     int64
 15  is_night                98 non-null     int64
 16  amount_vs_user_avg      98 non-null     float64
 17  amount_vs_user_max      98 non-null     float64
 18  is_amount_outlier       98 non-null     int64
 19  time_since_last_tx      96 non-null     float64
 20  tx_last_24h             98 non-null     int64
 21  is_preferred_type       98 non-null     int64
 22  amount_velocity_24h     98 non-null     float64
 23  amount_risk             98 non-null     float64
 24  velocity_risk           98 non-null     float64
 25  frequency_risk          98 non-null     float64
 26  time_risk               98 non-null     float64
 27  type_risk               98 non-null     float64
 28  risk_score              98 non-null     float64
 29  is_suspicious           98 non-null     int64
dtypes: float64(14), int32(2), int64(7), object(7)
memory usage: 23.0+ KB

# Custom risk thresholds

In [53]:
# Custom risk thresholds
risk_thresholds = {
    'amount_multiplier': 2.5,      # More sensitive to amount
    'velocity_threshold': 1.5,     # More sensitive to velocity
    'tx_frequency_threshold': 4,   # Flag after 4 transactions in 24h
    'min_risk_score': 0.6         # Lower threshold for suspicious flag
}

# With user-specific rules
user_baselines = {
    'user_id': {
        'amount_threshold': 1000,
        'allowed_types': ['bank_transfer']
    }
}

features = engineer_fraud_features(
    selected_df,
    user_baselines=user_baselines,
    risk_thresholds=risk_thresholds
)

<ipython-input-44-1e6ebcd4f255>:61: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  features['tx_last_24h'] = features.groupby('user_id').apply(
<ipython-input-44-1e6ebcd4f255>:78: RuntimeWarning: invalid value encountered in scalar divide
  return recent_amount / (group['user_avg_amount'].iloc[0] * hours/24)
<ipython-input-44-1e6ebcd4f255>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  features['amount_velocity_24h'] = features.groupby('user_id').apply(

In [54]:
# View suspicious transactions
suspicious_tx = features[features['is_suspicious'] == 1]

suspicious_tx.head(10)

,TransID,user_id,user_name,type,amount,Currency,TransType,Status,user_avg_amount,user_std_amount,...,amount_velocity_24h,amount_risk,velocity_risk,frequency_risk,time_risk,type_risk,risk_score,is_suspicious,exceeds_user_threshold,is_allowed_type
4,GTB0101202308343978syrg8qwg,218/153955/1/5107/0,KASUJJA ARNOLD,MTN,31000.0,UGX,B2W,SUCCESS,324390.259259,6.873366e+05,...,0.072280,0.082835,0.193454,0.047426,0.2,0.0,0.106841,1,1.0,0.0
5,GTB0101202308365378syrg8qwg,218/153955/1/5107/0,KASUJJA ARNOLD,AIRTEL,21000.0,UGX,B2W,SUCCESS,324390.259259,6.873366e+05,...,0.033495,0.080523,0.187474,0.047426,0.2,0.5,0.154537,1,1.0,0.0
86,GTB0102202310235578syrg8qwg,218/154274/1/5107/0,abdul ssali,GTBANK,997500.0,UGX,OWN,SUCCESS,156882.061611,3.549624e+05,...,5.965429,0.979332,0.988631,0.119203,0.0,0.5,0.663764,1,NaN,NaN
152,GTB0103202308374078syrg8qwg,218/135560/1/5107/0,RITA ANYANGO,GTBANK,3000000.0,,INTERNAL,SUCCESS,417192.771084,8.359839e+05,...,3.881079,0.990905,0.915373,0.119203,0.0,0.5,0.649501,1,NaN,NaN
222,GTB0103202317323478syrg8qwg,218/157854/1/5107/0,nuhu,MTN,220000.0,UGX,B2W,SUCCESS,49434.057971,7.920189e+04,...,4.029851,0.875487,0.926208,0.500000,0.0,0.0,0.637973,1,NaN,NaN
526,GTB0107202317022278syrg8qwg,218/149253/1/5107/0,Mwesigye Robert,GTBANK,500000.0,,INTERNAL,SUCCESS,148890.825688,1.971830e+05,...,3.456282,0.702277,0.876130,0.500000,0.2,0.5,0.634830,1,NaN,NaN
680,GTB0109202320134078syrg8qwg,218/151119/1/5003/0,Shado Allan Sserwadda,MTN,1450000.0,UGX,B2W,SUCCESS,71431.237113,1.524818e+05,...,2.406057,1.000000,0.712193,0.268941,0.0,0.5,0.631836,1,NaN,NaN
884,GTB0112202316362152e323ed9e,218/145972/1/5003/0,Manzi Fortunate,Centenary Bank,3600000.0,UGX,OUTWARD,SUCCESS,480644.502538,9.760772e+05,...,3.513487,0.993240,0.882206,0.047426,0.0,0.5,0.627671,1,NaN,NaN
939,GTB011320231310097729F56A-0,211/108542/1/5002/0,amir hirani ali nehl,Centenary Bank,3000000.0,UGX,OUTWARD,SUCCESS,654636.363636,7.143010e+05,...,5.557047,0.889210,0.982994,0.268941,0.0,0.5,0.660760,1,NaN,NaN
1243,GTB0117202315531678syrg8qwg,218/144863/1/5003/0,JORDAN KALYABE,GTBANK,5800000.0,UGX,OWN,SUCCESS,655515.362776,1.536056e+06,...,4.950673,0.998253,0.969251,0.268941,0.0,0.5,0.695490,1,NaN,NaN